# ─── hypridle ────────────────────────────────────────────────────────────
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Atenuar backlight al minuto
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Bloquear a los 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar pantallas a los 6 min
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspender a los 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
