# ─── hyprpaper ───────────────────────────────────────────────────────────
preload = ~/Pictures/wallpapers/aurora-iceland.jpg
wallpaper = , ~/Pictures/wallpapers/aurora-iceland.jpg
splash = false
ipc = on
